### ISSUE TITLE
系统找不到指定的路径。: '/data/catndog/train/image',已经建立了文件夹，怎么还是报错

### ISSUE THREAD

**Issue by Monologuethl** [HZCTony/U-net-with-multiple-classification#1]
D:\TONG\github\U-net-multiclass\model2.py:79: UserWarning: Update your `Model` call to the Keras 2 API: `Model(inputs=Tensor("in..., outputs=Tensor("co...)`
  model = Model(input=inputs, output=conv10)
Epoch 1/20
Traceback (most recent call last):
  File "D:/TONG/github/U-net-multiclass/main.py", line 21, in <module>
    model.fit_generator(myGene, steps_per_epoch=100, epochs=20, callbacks=[model_checkpoint])
  File "C:\Users\Tong\AppData\Local\Programs\Python\Python36\lib\site-packages\keras\legacy\interfaces.py", line 91, in wrapper
    return func(*args, **kwargs)
  File "C:\Users\Tong\AppData\Local\Programs\Python\Python36\lib\site-packages\keras\engine\training.py", line 1418, in fit_generator
    initial_epoch=initial_epoch)
  File "C:\Users\Tong\AppData\Local\Programs\Python\Python36\lib\site-packages\keras\engine\training_generator.py", line 181, in fit_generator
    generator_output = next(output_generator)
  File "C:\Users\Tong\AppData\Local\Programs\Python\Python36\lib\site-packages\keras\utils\data_utils.py", line 709, in get
    six.reraise(*sys.exc_info())
  File "C:\Users\Tong\AppData\Local\Programs\Python\Python36\lib\site-packages\six.py", line 693, in reraise
    raise value
  File "C:\Users\Tong\AppData\Local\Programs\Python\Python36\lib\site-packages\keras\utils\data_utils.py", line 685, in get
    inputs = self.queue.get(block=True).get()
  File "C:\Users\Tong\AppData\Local\Programs\Python\Python36\lib\multiprocessing\pool.py", line 644, in get
    raise self._value
  File "C:\Users\Tong\AppData\Local\Programs\Python\Python36\lib\multiprocessing\pool.py", line 119, in worker
    result = (True, func(*args, **kwds))
  File "C:\Users\Tong\AppData\Local\Programs\Python\Python36\lib\site-packages\keras\utils\data_utils.py", line 626, in next_sample
    return six.next(_SHARED_SEQUENCES[uid])
  File "D:\TONG\github\U-net-multiclass\data.py", line 58, in trainGenerator
    seed=seed)
  File "C:\Users\Tong\AppData\Local\Programs\Python\Python36\lib\site-packages\keras_preprocessing\image.py", line 1013, in flow_from_directory
    interpolation=interpolation)
  File "C:\Users\Tong\AppData\Local\Programs\Python\Python36\lib\site-packages\keras_preprocessing\image.py", line 1875, in __init__
    for subdir in sorted(os.listdir(directory)):
FileNotFoundError: [WinError 3] 系统找不到指定的路径。: '/data/catndog/train/image'

**Comment by HZCTony** [comment]
can you explain how you set your image path for training?

請問你可以解釋一下你怎麼設置圖檔路徑的嗎？

> D:\TONG\github\U-net-multiclass\model2.py:79: UserWarning: Update your `Model` call to the Keras 2 API: `Model(inputs=Tensor("in..., outputs=Tensor("co...)`
> model = Model(input=inputs, output=conv10)
> Epoch 1/20
> Traceback (most recent call last):
> File "D:/TONG/github/U-net-multiclass/main.py", line 21, in 
> model.fit_generator(myGene, steps_per_epoch=100, epochs=20, callbacks=[model_checkpoint])
> File "C:\Users\Tong\AppData\Local\Programs\Python\Python36\lib\site-packages\keras\legacy\interfaces.py", line 91, in wrapper
> return func(*args, **kwargs)
> File "C:\Users\Tong\AppData\Local\Programs\Python\Python36\lib\site-packages\keras\engine\training.py", line 1418, in fit_generator
> initial_epoch=initial_epoch)
> File "C:\Users\Tong\AppData\Local\Programs\Python\Python36\lib\site-packages\keras\engine\training_generator.py", line 181, in fit_generator
> generator_output = next(output_generator)
> File "C:\Users\Tong\AppData\Local\Programs\Python\Python36\lib\site-packages\keras\utils\data_utils.py", line 709, in get
> six.reraise(*sys.exc_info())
> File "C:\Users\Tong\AppData\Local\Programs\Python\Python36\lib\site-packages\six.py", line 693, in reraise
> raise value
> File "C:\Users\Tong\AppData\Local\Programs\Python\Python36\lib\site-packages\keras\utils\data_utils.py", line 685, in get
> inputs = self.queue.get(block=True).get()
> File "C:\Users\Tong\AppData\Local\Programs\Python\Python36\lib\multiprocessing\pool.py", line 644, in get
> raise self._value
> File "C:\Users\Tong\AppData\Local\Programs\Python\Python36\lib\multiprocessing\pool.py", line 119, in worker
> result = (True, func(*args, **kwds))
> File "C:\Users\Tong\AppData\Local\Programs\Python\Python36\lib\site-packages\keras\utils\data_utils.py", line 626, in next_sample
> return six.next(_SHARED_SEQUENCES[uid])
> File "D:\TONG\github\U-net-multiclass\data.py", line 58, in trainGenerator
> seed=seed)
> File "C:\Users\Tong\AppData\Local\Programs\Python\Python36\lib\site-packages\keras_preprocessing\image.py", line 1013, in flow_from_directory
> interpolation=interpolation)
> File "C:\Users\Tong\AppData\Local\Programs\Python\Python36\lib\site-packages\keras_preprocessing\image.py", line 1875, in **init**
> for subdir in sorted(os.listdir(directory)):
> FileNotFoundError: [WinError 3] 系统找不到指定的路径。: '/data/catndog/train/image'

**Comment by HZCTony** [comment]
若我理解沒錯的話，應該是'./data/catndog/train/image' 而非 '/data/catndog/train/image'。從本地端開始的相對路徑
