### ISSUE TITLE
import ERROR

### ISSUE THREAD

**Issue by erolgerceker** [HZCTony/U-net-with-multiple-classification#6]
Traceback (most recent call last):
  File "main.py", line 3, in <module>
    from model import *
  File "C:\Users\GoLive_Erol\Desktop\Unet-with-multiple-classification\model.py", line 12, in <module>
    from tensorflow.contrib.opt import AdamWOptimizer
ModuleNotFoundError: No module named 'tensorflow.contrib'

i m using tf 2.3

**Comment by erolgerceker** [comment]
while using tf 1.15 . i m getting this error


ImportError: Keras requires TensorFlow 2.2 or higher. Install TensorFlow via `pip install tensorflow`
